declare function u(): string;
declare function g(): void;
declare function s(e: any): void;
declare function E(e: any, t: any): void;
declare function l(e: any, t: any): void;
declare var r: any;
declare var n: any;
declare var i: string;
declare var c: string;
declare var d: string;
