using System.Text.Json.Serialization;

namespace Extension.Services.SignifyService.Models {
    /// <summary>
    /// Represents a BIP39 challenge word list for authentication.
    /// Generated by KERIA agent using the challenges.generate() method.
    /// </summary>
    public record Challenge(
        [property: JsonPropertyName("words")] List<string> Words
    );

    /// <summary>
    /// Result from marking a challenge response as accepted.
    /// </summary>
    public record ChallengeRespondedResult(
        [property: JsonPropertyName("ok")] bool Ok,
        [property: JsonPropertyName("status")] int Status
    );
}
