# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Build and Upload Artifacts

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore

    - name: Debug Environment Variables
      run: echo "GITHUB_SHA=$GITHUB_SHA"

    - name: Set short commit hash
      run: echo "SHORT_COMMIT_HASH=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

    - name: Build with MSBuild
      run: dotnet build --configuration Release --no-restore

    - name: Post-build compute release_name for manifest.json
      id: get_version_wwwroot
      run: |
          # Extract the version value from wwwroot/manifest.json
          version=$(jq -r '.version' KeriAuth.BrowserExtension/bin/Release/net8.0/wwwroot/manifest.json)
          echo "version=$version" >> $GITHUB_ENV  # Save the version to the environment variable
          echo "Version extracted from KeriAuth.BrowserExtension/bin/Release/net8.0/wwwroot/manifest.json: $version"

    - name: Modify version_name in wwwroot/manifest.json
      run: |
         # Get the version string from the environment variable
         new_version_name="${{ env.version }}-${{ env.commit_hash }}"
         
         # Modify the version_name in the KeriAuth.BrowserExtension/wwwroot/manifest.json file
         jq --arg new_version_name "$new_version_name" \
            '.version_name = $new_version_name' \
            wwwroot/manifest.json > temp.json && mv temp.json KeriAuth.BrowserExtension/bin/Release/net8.0/wwwroot/manifest.json

    - name: Modify version_name in browserextension/wwwroot/manifest.json
      run: |
          # Get the version string from the environment variable
          new_version_name="${{ env.version }}-${{ env.commit_hash }}"
          
          # Modify the version_name in the browserextension/wwwroot/manifest.json file
          jq --arg new_version_name "$new_version_name" \
             '.version_name = $new_version_name' \
             browserextension/wwwroot/manifest.json > temp.json && mv temp.json KeriAuth.BrowserExtension/bin/Release/net8.0/browserextension/wwwroot/manifest.json

    - name: Display modified version_name
      run: |
          # Display the modified manifest files to confirm the changes
          cat KeriAuth.BrowserExtension/bin/Release/net8.0/wwwroot/manifest.json
          cat KeriAuth.BrowserExtension/bin/Release/net8.0/browserextension/wwwroot/manifest.json

    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal

    - name: Zip artifacts
      run: |
        cd /home/runner/work/keriauth-blazor-wasm/keriauth-blazor-wasm/KeriAuth.BrowserExtension/bin/Release/net8.0/browserextension/
        zip -r /home/runner/work/KeriAuth.zip *
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: /home/runner/work/KeriAuth.zip
      
