# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Build and Upload Artifacts

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore

    - name: Debug Environment Variables
      run: echo "GITHUB_SHA=$GITHUB_SHA"

    - name: Set short commit hash
      run: echo "SHORT_COMMIT_HASH=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

    - name: Build with MSBuild
      run: dotnet build --configuration Release --no-restore /p:CommitHash=$SHORT_COMMIT_HASH

    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal

    - name: Zip artifacts
      run: |
        cd /home/runner/work/keriauth-blazor-wasm/keriauth-blazor-wasm/KeriAuth.BrowserExtension/bin/Release/net8.0/browserextension/
        zip -r /home/runner/work/KeriAuth.zip *
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: /home/runner/work/KeriAuth.zip
      
