namespace Extension.Models;

/// <summary>
/// Represents a logical grouping of ports (ContentScript + attached App ports) for a specific tab.
///
/// Terminology note: "PortSession" is distinct from:
/// - Storage session (chrome.storage.session / StorageArea.Session)
/// - KERIA session (authenticated connection via signify-ts)
/// </summary>
public record PortSession {
    /// <summary>
    /// Unique identifier for this PortSession, generated by BackgroundWorker.
    /// </summary>
    public required Guid PortSessionId { get; init; }

    /// <summary>
    /// Tab ID this PortSession is associated with. Null for non-tab-scoped sessions.
    /// </summary>
    public int? TabId { get; init; }

    /// <summary>
    /// Frame ID within the tab. Null for main frame or non-tab-scoped sessions.
    /// </summary>
    public int? FrameId { get; init; }

    /// <summary>
    /// Port ID of the ContentScript connection. Null if CS not yet connected.
    /// Note: We use port IDs (strings) rather than Port objects because Port objects
    /// cannot reliably serve as dictionary keys across JS interop boundaries.
    /// </summary>
    public string? ContentScriptPortId { get; set; }

    /// <summary>
    /// List of App port IDs attached to this PortSession.
    /// Typically only one App (popup or sidepanel) is attached at a time.
    /// </summary>
    public List<string> AttachedAppPortIds { get; } = [];

    /// <summary>
    /// Timestamp when this PortSession was created.
    /// </summary>
    public DateTime CreatedAtUtc { get; init; } = DateTime.UtcNow;

    /// <summary>
    /// Gets the tab key used for dictionary lookups.
    /// Format: "{tabId}:{frameId}"
    /// </summary>
    /// <exception cref="InvalidOperationException">Thrown if TabId is null.</exception>
    public string GetTabKey() {
        if (!TabId.HasValue) {
            throw new InvalidOperationException("Cannot get tab key for a PortSession without TabId");
        }
        return $"{TabId}:{FrameId ?? 0}";
    }

    /// <summary>
    /// Checks if this PortSession has an active ContentScript connection.
    /// </summary>
    public bool HasContentScript => !string.IsNullOrEmpty(ContentScriptPortId);

    /// <summary>
    /// Checks if this PortSession has any attached App connections.
    /// </summary>
    public bool HasAttachedApps => AttachedAppPortIds.Count > 0;

    /// <summary>
    /// Checks if this PortSession is empty (no CS and no App connections).
    /// </summary>
    public bool IsEmpty => !HasContentScript && !HasAttachedApps;
}
